import streamlit as st

st.write("This app is under construction.")

url="https://github.com/zn2jae/streamlit25/raw/main/images/image01.png"
st.image(url, caption="This image is generated by an AI", width=600)  # width in pixels

